config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students
  get 'home/index'
  get 'results/result'
  get 'home/about'
  #get '/result'=>'results#result'
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
    has_many:results
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :course
  belongs_to :student

 # def self.search(search)
  #  if search
   #   usn_type=Student.find_by(usn: search)
  #    if usn_type
  #      self.where(student_id: usn_type)
  #    else
  #      @results=Results.all
  #    end
  #  else
  #    @results=Result.all
  #  end
  #end

end

app/models/student.rb
class Student < ApplicationRecord
    has_many:results
    has_many:courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:course_code, :course_name, :cee_marks, :see_marks)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def results
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
    def result
      #@results=Result.search(params[:search])
     
        @usn_id=params[:search]
        @learners=Student.all.where("lower(usn) LIKE :search",search: "%#{@usn_id}%")
        @ids= []

        @learners.each do |learner|
          #@ids <<learner.id#1,2..
          @ids <<learner.id
        end
       # @marks=Result.all.where("student_id in #{@ids}")
       @marks=Result.where(student_id: @ids)
       @courseids=@marks.map(&:course_id)
        #@marks.each do |mark|
         #  @courseids=mark.course_id
        #end
           @subs=Course.all.where(id: @courseids)


           
    end
end
        #@marks=Student.all.where("lower(usn) LIKE :search",search: "%#{@usn_id}%")

#private
 #def result_params
 #   params.require(:result).permit(:usn, :search)
#end
 

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:usn, :name, :gender, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_course.html.erb
<table>
<div id="<%= dom_id course %>">

    <tr><th><strong>Course code:</strong></th><th><strong>Course name:</strong></th><th><strong>Cee marks:</strong></th><th><strong>See marks:</strong></th></tr>
    
   <tr><td> <%= course.course_code %>
  </td>

  <td>
    <%= course.course_name %>
</td>
   <td> <%= course.cee_marks %>
</td>
   <td> <%= course.see_marks %>
  </td>
</tr>
</div>
</table>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :course_code, style: "display: block" %>
    <%= form.text_field :course_code %>
  </div>

  <div>
    <%= form.label :course_name, style: "display: block" %>
    <%= form.text_field :course_name %>
  </div>

  <div>
    <%= form.label :cee_marks, style: "display: block" %>
    <%= form.number_field :cee_marks %>
  </div>

  <div>
    <%= form.label :see_marks, style: "display: block" %>
    <%= form.number_field :see_marks %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
<table>
<tr><td>
  <%= link_to "Show this course", @course %> |
  </td> </tr>
  </table>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>


<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>course code</th>
      <th>course name</th>
      <th>cee max marks</th>
      <th>see max marks</th>
     <th> </th>
     <th> </th>

    </tr>
  </thead>

  <tbody>



  <% @courses.each do |course| %>
    <tr>
    <td>
    <%= course.course_code %>


    </td>
    
    <td><%= course.course_name %></td>
    <td><%= course.cee_marks %></td>
    <td><%= course.see_marks %></td>
    
    
    <td>
      <%= link_to "Show this course", course %>
</td>
<td><%= link_to 'Delete',course, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
        
</tr>
<% end %>

</tbody>
</table>
<br>
<%= link_to "New course", new_course_path, class:"btn btn-secondary" %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path ,class:"btn btn-dark"%>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="jumbotron">
  <h1 class="display-4">
    <%= @course.course_name %>
   
  </h1>
  <p class="lead">
    
    <%= @course.course_code %>  |  
    <%= @course.cee_marks %> |
    <%= @course.see_marks %>  
  </p>
  <br/>
  <%= link_to "Edit this course", edit_course_path(@course) , class:"btn btn-secondary"%> 
  <%= link_to "Destroy this course", @course, method: :delete , data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  
  <%= link_to "Back to courses", courses_path , class:"btn btn-dark"%>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container-fluid">
<%= link_to 'students app', home_index_path, class:"navbar-brand"%>

  
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    
      <li class="nav-item">
   <%= link_to 'about us', home_about_path, class:"nav-link"%>
        
      </li>
      <li class="nav-item">
      <%= link_to 'students list', students_path, class:"nav-link"%>
           
         </li>
         <li class="nav-item">
         <%= link_to 'add students ', new_student_path, class:"nav-link"%>
              
        </li>

            <li class="nav-item">
            <%= link_to 'courses list', courses_path, class:"nav-link"%>
                 
               </li>
               <li class="nav-item">
               <%= link_to 'add courses ', new_course_path, class:"nav-link"%>
                    
                  </li> 
                  <li class="nav-item">
                  <%= link_to 'results ', results_result_path, class:"nav-link"%>
                       
                     </li>     
    </ul>
    
  </div>
</div>
</nav>

app/views/home/about.html.erb
<div class:"container" style="background-color:lightblue">
<center>
<h1>about this website</h1>
<%= image_tag "about4.jpg", height: 200%>

<br>
<p>In this website students are assigned courses followed by CRUD operations</p>
<p>Based on marks scored by each student results are displayed</p>
<%= image_tag "about3.jpg", height: 200%> &nbsp
<%= image_tag "about2.webp", height: 200%>
<br>
<br>
</center>
</div>

app/views/home/index.html.erb
<div class="container" style="background-color:lightblue">
<br>
<center><h1>welcome to students results website</h1>
<%= image_tag "index.jpeg", height: 500%>
<br><br>
<quotes><b><i>" The best way to predict your future is to create it " </i>
<br>~Abraham Lincoln</b></quotes>
</center>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>students app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>

  <%= render 'home/header'%>
  <div class="container">
  <br/>
    <%= yield %>
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/results/result.html.erb
<%= form_tag(results_result_path, :method=>"get" )do %>
<%= label_tag(:search, "enter usn:")%>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag("search", :usn=>nil)%>  
<% end %>




<%@learners.each do |learner|%>
<h1>usn</h1>   <%= learner.usn%>
<h2>name</h2> <%= learner.name%>
<%end%>  



<div class="row">
<div class="table-responsive col-md-6">
  
   

<table class="table table-bordered">

     <tr><th> course code</th><th>course name</th></tr>

     <%@subs.each do |sub|%>
       <tr>
       <td><%= sub.course_code%></td><td><%= sub.course_name%></td>
       </tr>
     <%end%>
</table>

</div>
<div class="table-responsive col-md-6">
 
  <table class="table table-bordered">

    <tr><th> total</th><th>remarks</th></tr>

    <%@marks.each do|mark|%>
      <tr><% @cee=mark.cee_obtained%>
      <% @see=mark.see_obtained%>

      <% @total= @cee+@see%>
      <td><%=@total%></td>

      <%if @total > 45 %>
            <td>  <%= "pass"%></td>
      <%else %>
            <td>  <%= "fail"%></td>
      <%end%>

      </tr>

    <%end%>
  </table>

</div>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :usn, style: "display: block" %>
    <%= form.text_field :usn %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.number_field :phone_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<table>

<div id="<%= dom_id student %>">
 
<tr> <th><strong>usn</strong></th><th><strong>name</strong></th><th><strong>gender</strong></th><th><strong>phone number</strong></th> </tr>
<tr><td><%= student.usn%></td>



<td>
<%= student.name %>

</td>
<td>
<%= student.gender %>
</td>


<td>
<%= student.phone_number %>
</td>
</tr>

</div>
</table>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
<table>
<tr><td>
  <%= link_to "Show this student", @student %> |
</td></tr>
  </table>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>


<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>usn</th>
      <th>name</th>
      <th>gender</th>
      <th>phone number</th>
     <th> </th>
     <th> </th>

    </tr>
  </thead>

  <tbody>


  <% @students.each do |student| %>
    <tr>
    <td>
    <%= student.usn%>


    </td>
    
    <td><%= student.name %></td>
    <td><%= student.gender %></td>
    <td><%= student.phone_number %></td>
    
    
    <td>
      <%= link_to "Show this student", student %>
   </td>

   <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
        
   </tr>
   <% end %>
 
</tbody>
</table>
<br>


<%= link_to "New student", new_student_path, class:"btn btn-secondary"%>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path ,class:"btn btn-dark"%>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="jumbotron">
  <h1 class="display-4">
    <%= @student.name %>
   
  </h1>
  <p class="lead">
    
    <%= @student.usn %>  |  
    <%= @student.gender %> |
    <%= @student.phone_number %>  
  </p>
  <br/>

  <%= link_to "Edit this student", edit_student_path(@student) , class:"btn btn-secondary"%> 
 
  <%= link_to "Destroy this student", @student, method: :delete , data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
  <%= link_to "Back to students", students_path , class:"btn btn-dark"%>
  </div>